apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  volumes:
    - name: redis-storage
      emptyDir: {}
  containers:
  - image: redis
    name: redis
    resources: {}
    volumeMounts:
      - name: redis-storage
        mountPath: /data/redis
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
